#pragma once

const int NUM_ATT = 2, LAST_POS_UPDATE = 0;
const int CONTROLLER_CLIENT = 0, PILOT_CLIENT = 1;

enum AV_CLIENT { CONTROLLER, PILOT };
enum UPDATE_TIMES { DEFAULT = 2000L };
enum VERSIONS { PROTO_VERSION = 32698 };
enum FLIGHT_RULES {IFR, VFR, SVFR};